p8105_hw3_jz3902
================
Jinghan Zhao
2024-10-11

## Problem 1

### Short description

``` r
library(p8105.datasets)
data("ny_noaa")

ny_noaa
```

    ## # A tibble: 2,595,176 × 7
    ##    id          date        prcp  snow  snwd tmax  tmin 
    ##    <chr>       <date>     <int> <int> <int> <chr> <chr>
    ##  1 US1NYAB0001 2007-11-01    NA    NA    NA <NA>  <NA> 
    ##  2 US1NYAB0001 2007-11-02    NA    NA    NA <NA>  <NA> 
    ##  3 US1NYAB0001 2007-11-03    NA    NA    NA <NA>  <NA> 
    ##  4 US1NYAB0001 2007-11-04    NA    NA    NA <NA>  <NA> 
    ##  5 US1NYAB0001 2007-11-05    NA    NA    NA <NA>  <NA> 
    ##  6 US1NYAB0001 2007-11-06    NA    NA    NA <NA>  <NA> 
    ##  7 US1NYAB0001 2007-11-07    NA    NA    NA <NA>  <NA> 
    ##  8 US1NYAB0001 2007-11-08    NA    NA    NA <NA>  <NA> 
    ##  9 US1NYAB0001 2007-11-09    NA    NA    NA <NA>  <NA> 
    ## 10 US1NYAB0001 2007-11-10    NA    NA    NA <NA>  <NA> 
    ## # ℹ 2,595,166 more rows

There are 2595176 rows and 7 columns in the dataset.

``` r
colMeans(is.na(ny_noaa))
```

    ##        id      date      prcp      snow      snwd      tmax      tmin 
    ## 0.0000000 0.0000000 0.0561958 0.1468960 0.2280331 0.4371025 0.4371264

We have missing values in `prcp`, `snow`, `snwd`, `tmax` and `tmin`
columns. Especially, there over 40% data is missing in `tmax` and
`tmin`, which is a rather huge proportion.

This issue may result in a large amount of observations being ignored
during data analysis, making the analysis results incomplete and unable
to reflect the true situation.

### Data cleaning

``` r
ny_noaa_clean = 
  ny_noaa %>% 
  mutate(
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin),
    year = lubridate::year(date),
    month = lubridate::month(date),
    day = lubridate::day(date),
    prcp = prcp / 10,
    tmax = tmax / 10,
    tmin = tmin / 10
  ) %>% 
  relocate(id, date, year, month, day)

ny_noaa_clean %>% 
  count(snow) %>% 
  arrange(desc(n)) %>% 
  head()
```

    ## # A tibble: 6 × 2
    ##    snow       n
    ##   <int>   <int>
    ## 1     0 2008508
    ## 2    NA  381221
    ## 3    25   31022
    ## 4    13   23095
    ## 5    51   18274
    ## 6    76   10173

1)  Data cleaning steps:

- Create variables: `year`, `month` and `day`

- Arrange the units of variables: `prcp`(mm), `snow`(mm), `snwd`(mm),
  `tmax`(degrees C), `tmin`(degrees C)

- Organize variables in a meaningful order

2)  For snowfall, the most commonly observed values is 0. Because the
    dataset covers the whole year, but snow usually occurs in winter,
    most observations do not have snow.

### Average tmax in Jan and Jul

``` r
month.labs = c("January", "July")
names(month.labs) = c(1, 7)

ny_noaa_clean %>% 
  filter(month %in% c(1, 7)) %>%
  group_by(id, year, month) %>% 
  summarize(avg_tmax = mean(tmax, na.rm = TRUE)) %>% 
  drop_na(avg_tmax) %>% 
  ggplot(aes(x = year, y = avg_tmax, color = id)) +
  geom_point() +
  geom_line() +
  facet_grid(. ~ month, 
             labeller = labeller(month = month.labs)) +
  labs(
    title = "Average Maximum Temperature in Each Station",
    x = "Year",
    y = "Average Max Temp (°C)",
    caption = "The average max temperature in January and in July in each station across years.") +
  viridis::scale_color_viridis(discrete = TRUE,
                               option = "viridis") +
  theme(legend.position = "none")
```

![](p8105_hw3_jz3902_files/figure-gfm/avg_tmax-1.png)<!-- -->

- Most of the time, the average maximum temperatures at different
  stations have similar trends: they rise or fall at the same time.

- According to the graph, outliers occurred in July between 1985-1990.
  To find out which years they are:

``` r
ny_noaa_clean %>% 
  filter(month == 7) %>%
  group_by(id, year, month) %>% 
  summarize(avg_tmax = mean(tmax, na.rm = TRUE)) %>% 
  drop_na(avg_tmax) %>% 
  arrange(avg_tmax) %>% 
  head()
```

    ## `summarise()` has grouped output by 'id', 'year'. You can override using the
    ## `.groups` argument.

    ## # A tibble: 6 × 4
    ## # Groups:   id, year [6]
    ##   id           year month avg_tmax
    ##   <chr>       <dbl> <dbl>    <dbl>
    ## 1 USC00308962  1988     7     14.0
    ## 2 USC00302454  2004     7     18.3
    ## 3 USC00308946  1984     7     19.1
    ## 4 USC00309389  2007     7     19.2
    ## 5 USC00306957  2000     7     19.8
    ## 6 USC00308248  2000     7     19.9

- Station USC00308962 have extreme low average temperatures (14.0
  degrees C) in January, 1988.

### tmax vs tmin + snowfall

``` r
hex_tmax_tmin = 
  ny_noaa_clean %>% 
  drop_na(tmin, tmax) %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex() +
  labs(
    title = "Hexbin Plot: tmax vs tmin",
    x = "Minimum Temperature (°C)",
    y = "Maximum Temperature (°C)") +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 8, angle = 45))
  

box_snowfall = 
  ny_noaa_clean %>% 
  select(year, snow) %>% 
  filter(snow > 0 & snow < 100) %>% 
  ggplot(aes(x = factor(year), y = snow)) +
  geom_boxplot(fill = "lightblue") +
  labs(title = "Distribution of Snowfall (between 0-100 mm)",
       x = "Year",
       y = "Snowfall (mm)") +
  theme(axis.text.x = element_text(size = 8,
                                   angle = 45, 
                                   hjust = 1))

hex_tmax_tmin + box_snowfall
```

![](p8105_hw3_jz3902_files/figure-gfm/tmax_tmin_snowfall-1.png)<!-- -->

## Problem 2

## Problem 3
